#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name
# after the first dash is displayed (refer to the example)
lists=$(ls)

for x in $lists; do
  echo "$x" | cut -d '_' -f2
done
