#!/usr/bin/env bash
# ssh file config
Host *
    PasswordAuthentication no
    IdentifyFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
